remote_theme: mmistakes/minimal-mistakes@4.16.3

title: "WeatherLink Developer Portal"

url: "https://weatherlink.github.io"

# logo: /assets/images/logo_100.png

after_footer_scripts:
- /assets/js/footer-copyright.js

include:
- _pages

plugins:
- jekyll-include-cache
